spark.master                     local[*]
spark.eventLog.enabled           true
spark.eventLog.dir               /tmp/spark-events
spark.history.fs.logDirectory    /tmp/spark-events
spark.scheduler.mode             FAIR
spark.scheduler.allocation.file  /Users/ignite/College/6TH SEM/bda lab/EL/conf/fairscheduler.xml
spark.sql.shuffle.partitions     8
spark.ui.enabled                 true
spark.driver.memory              2g
